# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authenticate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SMSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsFrom', models.IntegerField(default=0)),
                ('smsTo', models.IntegerField(default=0)),
                ('smsText', models.CharField(max_length=121)),
                ('smsTime', models.DateTimeField(auto_now_add=True)),
                ('smsUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.Authenticate')),
            ],
        ),
    ]
