# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsdata',
            name='smsFrom',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='smsdata',
            name='smsTo',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
